# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160525_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcdissue',
            name='alt_large_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='alt_medium_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='alt_small_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='large_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='medium_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='small_url',
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='alt_large_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='alt_medium_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='alt_small_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='large_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='medium_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
    ]
