# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(serialize=False, primary_key=True)),
                ('issue_count', models.IntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True)),
                ('year_ended_uncertain', models.BooleanField(db_index=True)),
                ('notes', models.TextField()),
                ('keywords', models.TextField(null=True)),
                ('url', models.URLField(default='', max_length=255, blank=True)),
                ('reserved', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'gcd_brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BrandEmblemGroup',
            fields=[
                ('brand_emblem_group_id', models.AutoField(serialize=False, primary_key=True)),
                ('brand', models.ForeignKey(null=True, to='inventory.Brand')),
            ],
            options={
                'db_table': 'gcd_brand_emblem_groups',
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='BrandGroup',
            fields=[
                ('brand_group_id', models.AutoField(serialize=False, primary_key=True)),
                ('issue_count', models.IntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True)),
                ('year_ended_uncertain', models.BooleanField(db_index=True)),
                ('notes', models.TextField()),
                ('keywords', models.TextField(null=True)),
                ('url', models.URLField(default='', max_length=255, blank=True)),
                ('reserved', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'gcd_brand_groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BrandUse',
            fields=[
                ('brand_use_id', models.AutoField(serialize=False, primary_key=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True)),
                ('year_ended_uncertain', models.BooleanField(db_index=True)),
                ('notes', models.TextField()),
                ('reserved', models.BooleanField(db_index=True, default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('emblem', models.ForeignKey(to='inventory.Brand', related_name='in_use')),
            ],
            options={
                'db_table': 'gcd_brand_uses',
                'ordering': ('publisher',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(serialize=False, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ec_carts',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comic_id', models.AutoField(serialize=False, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_cgc_rated', models.BooleanField(default=False)),
                ('age', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze'), (4, 'Copper')], blank=True)),
                ('cgc_rating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], choices=[(10.0, 'Gem Mint'), (9.9, 'Mint'), (9.8, 'Near Mint/Mintt'), (9.6, 'Near Mint +'), (9.4, 'Near Mint'), (9.2, 'Near Mint -'), (9.0, 'Very Fine/Near Mint'), (8.5, 'Very Fine +'), (8.0, 'Very Fine'), (7.5, 'Very Fine -'), (7.0, 'Fine/Very Fine'), (6.5, 'Fine +'), (6.0, 'Fine'), (5.5, 'Fine -'), (5.0, 'Very Good/Fine'), (4.5, 'Very Good +'), (4.0, 'Very Good'), (3.5, 'Very Good -'), (3.0, 'Good/Very Good'), (2.5, 'Good +'), (2.0, 'Good'), (1.8, 'Good -'), (1.5, 'Fair/Good'), (1.0, 'Fair'), (0.5, 'Poor')], blank=True)),
                ('label_colour', models.CharField(null=True, choices=[('Purple', 'Purple'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow')], max_length=63, blank=True)),
                ('condition_rating', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], choices=[(10, 'Near Mint'), (8, 'Very Fine'), (6, 'Fine'), (4, 'Very Good'), (2, 'Good'), (1, 'Fair'), (0, 'Poor')], blank=True)),
                ('is_canadian_priced_variant', models.BooleanField(default=False)),
                ('is_variant_cover', models.BooleanField(default=False)),
                ('is_retail_incentive_variant', models.BooleanField(default=False)),
                ('is_newsstand_edition', models.BooleanField(default=False)),
                ('price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], blank=True)),
                ('cost', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], blank=True)),
            ],
            options={
                'db_table': 'ec_comics',
                'ordering': ('issue',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(serialize=False, primary_key=True)),
                ('code', models.CharField(unique=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'gcd_countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(serialize=False, primary_key=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('email', models.EmailField(null=True, unique=True, max_length=254, blank=True)),
                ('phone', models.CharField(null=True, max_length=15, blank=True)),
                ('street_name', models.CharField(max_length=63)),
                ('street_number', models.CharField(max_length=15)),
                ('unit_number', models.CharField(null=True, max_length=15, blank=True)),
                ('city', models.CharField(max_length=63)),
                ('province', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('postal', models.CharField(max_length=31)),
                ('has_consented', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ec_customers',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(serialize=False, primary_key=True)),
                ('role', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], choices=[(0, 'Owner'), (1, 'Manager'), (2, 'Worker')], default=0)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('street_name', models.CharField(max_length=63)),
                ('street_number', models.CharField(max_length=15)),
                ('unit_number', models.CharField(null=True, max_length=15, blank=True)),
                ('city', models.CharField(max_length=63)),
                ('province', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('postal', models.CharField(max_length=31)),
                ('email', models.EmailField(null=True, max_length=254, blank=True)),
                ('phone', models.CharField(null=True, max_length=15, blank=True)),
            ],
            options={
                'db_table': 'ec_employees',
                'ordering': ('employee_id',),
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('help_id', models.AutoField(serialize=False, primary_key=True)),
                ('subject', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], choices=[(1, 'Feedback'), (2, 'Error'), (3, 'Checkout'), (4, 'Inventory'), (5, 'Pull List'), (6, 'Sales'), (7, 'Emailing List'), (8, 'Store Settings / Users'), (9, 'Dashboard')], default=1)),
                ('subject_url', models.URLField(null=True, blank=True)),
                ('message', models.TextField(null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(to='inventory.Employee')),
            ],
            options={
                'db_table': 'ec_help_requests',
                'ordering': ('submission_date',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(serialize=False, primary_key=True)),
                ('type', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(null=True, upload_to='uploads')),
            ],
            options={
                'db_table': 'gcd_images',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('upload_id', models.AutoField(serialize=False, primary_key=True)),
                ('upload_date', models.DateField(null=True, auto_now=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='upload', blank=True)),
                ('user', models.ForeignKey(null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ec_image_uploads',
                'ordering': ('upload_date',),
            },
        ),
        migrations.CreateModel(
            name='IndiciaPublisher',
            fields=[
                ('indicia_publisher_id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('year_began', models.PositiveSmallIntegerField(null=True, db_index=True)),
                ('year_ended', models.PositiveSmallIntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True, default=False)),
                ('year_ended_uncertain', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(null=True, blank=True)),
                ('url', models.URLField(null=True, default='', max_length=255, blank=True)),
                ('is_surrogate', models.BooleanField(db_index=True)),
                ('reserved', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('imprint_count', models.IntegerField(default=0)),
                ('brand_count', models.IntegerField(db_index=True, default=0)),
                ('indicia_publisher_count', models.IntegerField(db_index=True, default=0)),
                ('series_count', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(to='inventory.Country')),
                ('images', models.ManyToManyField(to='inventory.Image')),
            ],
            options={
                'db_table': 'gcd_indicia_publishers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(serialize=False, primary_key=True)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('no_title', models.BooleanField(db_index=True, default=False)),
                ('volume', models.CharField(db_index=True, max_length=50)),
                ('no_volume', models.BooleanField(db_index=True, default=False)),
                ('display_volume_with_number', models.BooleanField(db_index=True, default=False)),
                ('isbn', models.CharField(db_index=True, max_length=32)),
                ('no_isbn', models.BooleanField(db_index=True, default=False)),
                ('valid_isbn', models.CharField(db_index=True, max_length=13)),
                ('variant_of_id', models.IntegerField(db_index=True, default=0)),
                ('variant_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(db_index=True, max_length=38)),
                ('no_barcode', models.BooleanField(default=False)),
                ('rating', models.CharField(db_index=True, max_length=255, default='')),
                ('no_rating', models.BooleanField(db_index=True, default=False)),
                ('is_first_issue', models.BooleanField(default=False)),
                ('is_last_issue', models.BooleanField(default=False)),
                ('publication_date', models.CharField(max_length=255)),
                ('key_date', models.CharField(db_index=True, max_length=10)),
                ('on_sale_date', models.CharField(db_index=True, max_length=10)),
                ('on_sale_date_uncertain', models.BooleanField(default=False)),
                ('sort_code', models.IntegerField(db_index=True)),
                ('indicia_frequency', models.CharField(max_length=255)),
                ('no_indicia_frequency', models.BooleanField(db_index=True, default=False)),
                ('price', models.CharField(max_length=255)),
                ('page_count', models.DecimalField(null=True, decimal_places=3, max_digits=10)),
                ('page_count_uncertain', models.BooleanField(default=False)),
                ('editing', models.TextField()),
                ('no_editing', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
                ('is_indexed', models.IntegerField(db_index=True, default=0)),
                ('reserved', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(db_index=True, auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('indicia_pub_not_printed', models.BooleanField(default=False)),
                ('no_brand', models.BooleanField(db_index=True, default=False)),
                ('small_url', models.URLField(null=True, max_length=255, blank=True)),
                ('medium_url', models.URLField(null=True, max_length=255, blank=True)),
                ('large_url', models.URLField(null=True, max_length=255, blank=True)),
                ('alt_small_url', models.URLField(null=True, max_length=255, blank=True)),
                ('alt_medium_url', models.URLField(null=True, max_length=255, blank=True)),
                ('alt_large_url', models.URLField(null=True, max_length=255, blank=True)),
                ('has_alternative', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(null=True, to='inventory.Brand')),
                ('images', models.ManyToManyField(to='inventory.Image')),
                ('indicia_publisher', models.ForeignKey(null=True, to='inventory.IndiciaPublisher')),
            ],
            options={
                'db_table': 'gcd_issues',
                'ordering': ['series', 'sort_code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(serialize=False, primary_key=True)),
                ('code', models.CharField(unique=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'gcd_languages',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(null=True, blank=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('street_name', models.CharField(max_length=63)),
                ('street_number', models.CharField(null=True, max_length=31, blank=True)),
                ('unit_number', models.CharField(null=True, max_length=15, blank=True)),
                ('city', models.CharField(max_length=63)),
                ('province', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('postal', models.CharField(max_length=31)),
                ('website', models.URLField(null=True, blank=True)),
                ('email', models.EmailField(null=True, max_length=254, blank=True)),
                ('phone', models.CharField(null=True, max_length=31, blank=True)),
                ('fax', models.CharField(null=True, max_length=31, blank=True)),
                ('twitter_url', models.URLField(null=True, blank=True)),
                ('facebook_url', models.URLField(null=True, blank=True)),
                ('instagram_url', models.URLField(null=True, blank=True)),
                ('linkedin_url', models.URLField(null=True, blank=True)),
                ('github_url', models.URLField(null=True, blank=True)),
                ('google_url', models.URLField(null=True, blank=True)),
                ('youtube_url', models.URLField(null=True, blank=True)),
                ('flickr_url', models.URLField(null=True, blank=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, to=settings.AUTH_USER_MODEL)),
                ('customers', models.ManyToManyField(to='inventory.Customer')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, null=True, to='inventory.ImageUpload')),
            ],
            options={
                'db_table': 'ec_organizations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(serialize=False, primary_key=True)),
                ('type', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], choices=[(1, 'Comic'), (2, 'Furniture'), (3, 'Coin'), (4, 'General')], default=1)),
                ('comic', models.ForeignKey(blank=True, null=True, to='inventory.Comic')),
            ],
            options={
                'db_table': 'ec_products',
                'ordering': ('product_id', 'type'),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('year_began', models.PositiveSmallIntegerField(null=True, db_index=True)),
                ('year_ended', models.PositiveSmallIntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True, default=False)),
                ('year_ended_uncertain', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(null=True, blank=True)),
                ('url', models.URLField(null=True, default='', max_length=255, blank=True)),
                ('is_master', models.BooleanField(db_index=True, default=False)),
                ('reserved', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('imprint_count', models.IntegerField(default=0)),
                ('brand_count', models.IntegerField(db_index=True, default=0)),
                ('indicia_publisher_count', models.IntegerField(db_index=True, default=0)),
                ('series_count', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(to='inventory.Country')),
                ('images', models.ManyToManyField(to='inventory.Image')),
                ('parent', models.ForeignKey(null=True, to='inventory.Publisher', related_name='imprint_set')),
            ],
            options={
                'db_table': 'gcd_publishers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(db_index=True, max_length=127)),
                ('organization', models.ForeignKey(to='inventory.Organization')),
            ],
            options={
                'db_table': 'ec_sections',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_name', models.CharField(db_index=True, max_length=255)),
                ('format', models.CharField(max_length=255, default='')),
                ('color', models.CharField(max_length=255, default='')),
                ('dimensions', models.CharField(max_length=255, default='')),
                ('paper_stock', models.CharField(max_length=255, default='')),
                ('binding', models.CharField(max_length=255, default='')),
                ('publishing_format', models.CharField(max_length=255, default='')),
                ('tracking_notes', models.TextField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('publication_notes', models.TextField(null=True, blank=True)),
                ('keywords', models.TextField(null=True, blank=True)),
                ('year_began', models.IntegerField(db_index=True)),
                ('year_ended', models.IntegerField(null=True, default=0, blank=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('publication_dates', models.CharField(max_length=255)),
                ('has_barcode', models.BooleanField(default=False)),
                ('has_indicia_frequency', models.BooleanField(default=False)),
                ('has_isbn', models.BooleanField(default=False)),
                ('has_issue_title', models.BooleanField(default=False)),
                ('has_volume', models.BooleanField(default=False)),
                ('has_rating', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('is_comics_publication', models.BooleanField(default=False)),
                ('is_singleton', models.BooleanField(default=False)),
                ('issue_count', models.IntegerField(null=True, default=0, blank=True)),
                ('has_gallery', models.BooleanField(db_index=True, default=False)),
                ('reserved', models.BooleanField(db_index=True, default=False)),
                ('open_reserve', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('cover_url', models.URLField(null=True, max_length=255, blank=True)),
                ('publication_type_id', models.IntegerField(null=True, blank=0)),
                ('country', models.ForeignKey(to='inventory.Country')),
                ('images', models.ManyToManyField(to='inventory.Image')),
                ('language', models.ForeignKey(to='inventory.Language')),
                ('publisher', models.ForeignKey(to='inventory.Publisher')),
            ],
            options={
                'db_table': 'gcd_series',
                'ordering': ['sort_name', 'year_began'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(null=True, blank=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('street_name', models.CharField(max_length=63)),
                ('street_number', models.CharField(null=True, max_length=31, blank=True)),
                ('unit_number', models.CharField(null=True, max_length=15, blank=True)),
                ('city', models.CharField(max_length=63)),
                ('province', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('postal', models.CharField(max_length=31)),
                ('website', models.URLField(null=True, blank=True)),
                ('email', models.EmailField(null=True, max_length=254, blank=True)),
                ('phone', models.CharField(null=True, max_length=31, blank=True)),
                ('fax', models.CharField(null=True, max_length=31, blank=True)),
                ('is_open_monday', models.BooleanField(default=False)),
                ('is_open_tuesday', models.BooleanField(default=False)),
                ('is_open_wednesday', models.BooleanField(default=False)),
                ('is_open_thursday', models.BooleanField(default=False)),
                ('is_open_friday', models.BooleanField(default=False)),
                ('is_open_saturday', models.BooleanField(default=False)),
                ('is_open_sunday', models.BooleanField(default=False)),
                ('monday_to', models.CharField(null=True, max_length=7, blank=True)),
                ('tuesday_to', models.CharField(null=True, max_length=7, blank=True)),
                ('wednesday_to', models.CharField(null=True, max_length=7, blank=True)),
                ('thursday_to', models.CharField(null=True, max_length=7, blank=True)),
                ('friday_to', models.CharField(null=True, max_length=7, blank=True)),
                ('saturday_to', models.CharField(null=True, max_length=7, blank=True)),
                ('sunday_to', models.CharField(null=True, max_length=7, blank=True)),
                ('monday_from', models.CharField(null=True, max_length=7, blank=True)),
                ('tuesday_from', models.CharField(null=True, max_length=7, blank=True)),
                ('wednesday_from', models.CharField(null=True, max_length=7, blank=True)),
                ('thursday_from', models.CharField(null=True, max_length=7, blank=True)),
                ('friday_from', models.CharField(null=True, max_length=7, blank=True)),
                ('saturday_from', models.CharField(null=True, max_length=7, blank=True)),
                ('sunday_from', models.CharField(null=True, max_length=7, blank=True)),
                ('employees', models.ManyToManyField(to='inventory.Employee')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, null=True, to='inventory.ImageUpload')),
                ('organization', models.ForeignKey(to='inventory.Organization')),
            ],
            options={
                'db_table': 'ec_stores',
                'ordering': ('store_id',),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.AutoField(serialize=False, primary_key=True)),
                ('title', models.CharField(max_length=255)),
                ('title_inferred', models.BooleanField(db_index=True, default=False)),
                ('feature', models.CharField(max_length=255)),
                ('sequence_number', models.IntegerField()),
                ('page_count', models.DecimalField(null=True, decimal_places=3, db_index=True, max_digits=10)),
                ('page_count_uncertain', models.BooleanField(db_index=True, default=False)),
                ('script', models.TextField()),
                ('pencils', models.TextField()),
                ('inks', models.TextField()),
                ('colors', models.TextField()),
                ('letters', models.TextField()),
                ('editing', models.TextField()),
                ('no_script', models.BooleanField(db_index=True, default=False)),
                ('no_pencils', models.BooleanField(db_index=True, default=False)),
                ('no_inks', models.BooleanField(db_index=True, default=False)),
                ('no_colors', models.BooleanField(db_index=True, default=False)),
                ('no_letters', models.BooleanField(db_index=True, default=False)),
                ('no_editing', models.BooleanField(db_index=True, default=False)),
                ('job_number', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=255)),
                ('characters', models.TextField()),
                ('synopsis', models.TextField()),
                ('reprint_notes', models.TextField()),
                ('notes', models.TextField()),
                ('keywords', models.TextField(null=True)),
                ('reserved', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(db_index=True, auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('issue', models.ForeignKey(to='inventory.Issue')),
            ],
            options={
                'db_table': 'gcd_stories',
                'ordering': ('sequence_number',),
            },
        ),
        migrations.CreateModel(
            name='StoryType',
            fields=[
                ('story_type_id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(unique=True, db_index=True, max_length=50)),
                ('sort_code', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'gcd_story_types',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.ForeignKey(to='inventory.StoryType'),
        ),
        migrations.AddField(
            model_name='section',
            name='store',
            field=models.ForeignKey(to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='issue',
            name='series',
            field=models.ForeignKey(null=True, to='inventory.Series'),
        ),
        migrations.AddField(
            model_name='indiciapublisher',
            name='parent',
            field=models.ForeignKey(null=True, to='inventory.Publisher'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='organization',
            field=models.ForeignKey(to='inventory.Organization'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='screenshot',
            field=models.ForeignKey(blank=True, null=True, to='inventory.ImageUpload'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='store',
            field=models.ForeignKey(to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(to='inventory.Organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, null=True, to='inventory.ImageUpload'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, to='inventory.ImageUpload'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comic',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, null=True, to='inventory.ImageUpload'),
        ),
        migrations.AddField(
            model_name='comic',
            name='images',
            field=models.ManyToManyField(to='inventory.ImageUpload', related_name='comic_images', blank=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='issue',
            field=models.ForeignKey(to='inventory.Issue'),
        ),
        migrations.AddField(
            model_name='comic',
            name='organization',
            field=models.ForeignKey(to='inventory.Organization'),
        ),
        migrations.AddField(
            model_name='comic',
            name='section',
            field=models.ForeignKey(to='inventory.Section'),
        ),
        migrations.AddField(
            model_name='comic',
            name='store',
            field=models.ForeignKey(to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, to='inventory.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, to='inventory.Employee'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='inventory.Product'),
        ),
        migrations.AddField(
            model_name='branduse',
            name='publisher',
            field=models.ForeignKey(to='inventory.Publisher'),
        ),
        migrations.AddField(
            model_name='brandgroup',
            name='parent',
            field=models.ForeignKey(null=True, to='inventory.Publisher'),
        ),
        migrations.AddField(
            model_name='brandemblemgroup',
            name='brandgroup',
            field=models.ForeignKey(null=True, to='inventory.BrandGroup'),
        ),
        migrations.AddField(
            model_name='brand',
            name='group',
            field=models.ManyToManyField(db_table='gcd_brand_emblem_group', to='inventory.BrandGroup', blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='images',
            field=models.ManyToManyField(to='inventory.Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='parent',
            field=models.ForeignKey(null=True, to='inventory.Publisher'),
        ),
    ]
