# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True)),
                ('year_ended_uncertain', models.BooleanField(db_index=True)),
                ('notes', models.TextField()),
                ('keywords', models.TextField(null=True)),
                ('url', models.URLField(max_length=255, blank=True, default='')),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
            ],
            options={
                'db_table': 'gcd_brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BrandEmblemGroup',
            fields=[
                ('brand_emblem_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(null=True, to='inventory.Brand')),
            ],
            options={
                'db_table': 'gcd_brand_emblem_groups',
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='BrandGroup',
            fields=[
                ('brand_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True)),
                ('year_ended_uncertain', models.BooleanField(db_index=True)),
                ('notes', models.TextField()),
                ('keywords', models.TextField(null=True)),
                ('url', models.URLField(max_length=255, blank=True, default='')),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
            ],
            options={
                'db_table': 'gcd_brand_groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BrandUse',
            fields=[
                ('brand_use_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True)),
                ('year_ended_uncertain', models.BooleanField(db_index=True)),
                ('notes', models.TextField()),
                ('reserved', models.BooleanField(default=0, db_index=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('emblem', models.ForeignKey(to='inventory.Brand', related_name='in_use')),
            ],
            options={
                'db_table': 'gcd_brand_uses',
                'ordering': ('publisher',),
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_cgc_rated', models.BooleanField(default=False)),
                ('age', models.PositiveSmallIntegerField(null=True, blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze'), (4, 'Copper')])),
                ('cgc_rating', models.FloatField(null=True, blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], choices=[(10.0, 'Gem Mint'), (9.9, 'Mint'), (9.8, 'Near Mint/Mintt'), (9.6, 'Near Mint +'), (9.4, 'Near Mint'), (9.2, 'Near Mint -'), (9.0, 'Very Fine/Near Mint'), (8.5, 'Very Fine +'), (8.0, 'Very Fine'), (7.5, 'Very Fine -'), (7.0, 'Fine/Very Fine'), (6.5, 'Fine +'), (6.0, 'Fine'), (5.5, 'Fine -'), (5.0, 'Very Good/Fine'), (4.5, 'Very Good +'), (4.0, 'Very Good'), (3.5, 'Very Good -'), (3.0, 'Good/Very Good'), (2.5, 'Good +'), (2.0, 'Good'), (1.8, 'Good -'), (1.5, 'Fair/Good'), (1.0, 'Fair'), (0.5, 'Poor')])),
                ('label_colour', models.CharField(max_length=63, null=True, blank=True, choices=[('Purple', 'Purple'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow')])),
                ('condition_rating', models.PositiveSmallIntegerField(null=True, blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], choices=[(10, 'Near Mint'), (8, 'Very Fine'), (6, 'Fine'), (4, 'Very Good'), (2, 'Good'), (1, 'Fair'), (0, 'Poor')])),
                ('is_canadian_priced_variant', models.BooleanField(default=False)),
                ('is_variant_cover', models.BooleanField(default=False)),
                ('is_retail_incentive_variant', models.BooleanField(default=False)),
                ('is_newsstand_edition', models.BooleanField(default=False)),
                ('price', models.FloatField(null=True, blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.FloatField(null=True, blank=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'ec_comics',
                'ordering': ('issue',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(unique=True, max_length=10)),
                ('name', models.CharField(max_length=255, db_index=True)),
            ],
            options={
                'db_table': 'gcd_countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], choices=[(0, 'Owner'), (1, 'Manager'), (2, 'Clerc'), (3, 'Cashier')], default=0)),
                ('image', models.ImageField(null=True, blank=True, upload_to='upload')),
            ],
            options={
                'db_table': 'ec_employees',
                'ordering': ('employee_id',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, db_index=True)),
                ('file', models.FileField(null=True, upload_to='uploads')),
            ],
            options={
                'db_table': 'gcd_images',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_assigned', models.BooleanField(default=False)),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('image', models.ImageField(null=True, blank=True, upload_to='upload')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.SET_NULL, null=True)),
            ],
            options={
                'db_table': 'ec_image_uploads',
                'ordering': ('upload_date',),
            },
        ),
        migrations.CreateModel(
            name='IndiciaPublisher',
            fields=[
                ('indicia_publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('year_began', models.PositiveSmallIntegerField(null=True, db_index=True)),
                ('year_ended', models.PositiveSmallIntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False, db_index=True)),
                ('year_ended_uncertain', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('url', models.URLField(max_length=255, null=True, blank=True, default='')),
                ('is_surrogate', models.BooleanField(db_index=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('imprint_count', models.IntegerField(default=0)),
                ('brand_count', models.IntegerField(default=0, db_index=True)),
                ('indicia_publisher_count', models.IntegerField(default=0, db_index=True)),
                ('series_count', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(to='inventory.Country')),
                ('images', models.ManyToManyField(to='inventory.Image')),
            ],
            options={
                'db_table': 'gcd_indicia_publishers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, db_index=True)),
                ('title', models.CharField(max_length=255, db_index=True)),
                ('no_title', models.BooleanField(default=False, db_index=True)),
                ('volume', models.CharField(max_length=50, db_index=True)),
                ('no_volume', models.BooleanField(default=False, db_index=True)),
                ('display_volume_with_number', models.BooleanField(default=False, db_index=True)),
                ('isbn', models.CharField(max_length=32, db_index=True)),
                ('no_isbn', models.BooleanField(default=False, db_index=True)),
                ('valid_isbn', models.CharField(max_length=13, db_index=True)),
                ('variant_of_id', models.IntegerField(default=0, db_index=True)),
                ('variant_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=38, db_index=True)),
                ('no_barcode', models.BooleanField(default=False)),
                ('rating', models.CharField(max_length=255, default='', db_index=True)),
                ('no_rating', models.BooleanField(default=False, db_index=True)),
                ('is_first_issue', models.BooleanField(default=False)),
                ('is_last_issue', models.BooleanField(default=False)),
                ('publication_date', models.CharField(max_length=255)),
                ('key_date', models.CharField(max_length=10, db_index=True)),
                ('on_sale_date', models.CharField(max_length=10, db_index=True)),
                ('on_sale_date_uncertain', models.BooleanField(default=False)),
                ('sort_code', models.IntegerField(db_index=True)),
                ('indicia_frequency', models.CharField(max_length=255)),
                ('no_indicia_frequency', models.BooleanField(default=False, db_index=True)),
                ('price', models.CharField(max_length=255)),
                ('page_count', models.DecimalField(max_digits=10, null=True, decimal_places=3)),
                ('page_count_uncertain', models.BooleanField(default=False)),
                ('editing', models.TextField()),
                ('no_editing', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
                ('is_indexed', models.IntegerField(default=0, db_index=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('indicia_pub_not_printed', models.BooleanField(default=False)),
                ('no_brand', models.BooleanField(default=False, db_index=True)),
                ('small_url', models.URLField(max_length=255, null=True, blank=True)),
                ('medium_url', models.URLField(max_length=255, null=True, blank=True)),
                ('large_url', models.URLField(max_length=255, null=True, blank=True)),
                ('alt_small_url', models.URLField(max_length=255, null=True, blank=True)),
                ('alt_medium_url', models.URLField(max_length=255, null=True, blank=True)),
                ('alt_large_url', models.URLField(max_length=255, null=True, blank=True)),
                ('has_alternative', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(null=True, to='inventory.Brand')),
                ('images', models.ManyToManyField(to='inventory.Image')),
                ('indicia_publisher', models.ForeignKey(null=True, to='inventory.IndiciaPublisher')),
            ],
            options={
                'db_table': 'gcd_issues',
                'ordering': ['series', 'sort_code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(unique=True, max_length=10)),
                ('name', models.CharField(max_length=255, db_index=True)),
            ],
            options={
                'db_table': 'gcd_languages',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, db_index=True)),
            ],
            options={
                'db_table': 'ec_locations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, blank=True, upload_to='upload')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(null=True, blank=True)),
                ('joined', models.DateField(null=True, blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('street_name', models.CharField(max_length=63)),
                ('street_number', models.CharField(max_length=31, null=True, blank=True)),
                ('unit_number', models.CharField(max_length=15, null=True, blank=True)),
                ('city', models.CharField(max_length=63)),
                ('province', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('postal', models.CharField(max_length=31)),
                ('website', models.URLField(null=True, blank=True)),
                ('email', models.EmailField(max_length=254, null=True, blank=True)),
                ('phone', models.CharField(max_length=31, null=True, blank=True)),
                ('fax', models.CharField(max_length=31, null=True, blank=True)),
                ('twitter_url', models.URLField(null=True, blank=True)),
                ('facebook_url', models.URLField(null=True, blank=True)),
                ('instagram_url', models.URLField(null=True, blank=True)),
                ('linkedin_url', models.URLField(null=True, blank=True)),
                ('github_url', models.URLField(null=True, blank=True)),
                ('google_url', models.URLField(null=True, blank=True)),
                ('youtube_url', models.URLField(null=True, blank=True)),
                ('flickr_url', models.URLField(null=True, blank=True)),
            ],
            options={
                'db_table': 'ec_organizations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('year_began', models.PositiveSmallIntegerField(null=True, db_index=True)),
                ('year_ended', models.PositiveSmallIntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False, db_index=True)),
                ('year_ended_uncertain', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('url', models.URLField(max_length=255, null=True, blank=True, default='')),
                ('is_master', models.BooleanField(default=False, db_index=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('imprint_count', models.IntegerField(default=0)),
                ('brand_count', models.IntegerField(default=0, db_index=True)),
                ('indicia_publisher_count', models.IntegerField(default=0, db_index=True)),
                ('series_count', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(to='inventory.Country')),
                ('images', models.ManyToManyField(to='inventory.Image')),
                ('parent', models.ForeignKey(to='inventory.Publisher', related_name='imprint_set', null=True)),
            ],
            options={
                'db_table': 'gcd_publishers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, db_index=True)),
                ('location', models.ForeignKey(to='inventory.Location')),
                ('organization', models.ForeignKey(to='inventory.Organization')),
            ],
            options={
                'db_table': 'ec_sections',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('sort_name', models.CharField(max_length=255, db_index=True)),
                ('format', models.CharField(max_length=255, default='')),
                ('color', models.CharField(max_length=255, default='')),
                ('dimensions', models.CharField(max_length=255, default='')),
                ('paper_stock', models.CharField(max_length=255, default='')),
                ('binding', models.CharField(max_length=255, default='')),
                ('publishing_format', models.CharField(max_length=255, default='')),
                ('tracking_notes', models.TextField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('publication_notes', models.TextField(null=True, blank=True)),
                ('keywords', models.TextField(null=True, blank=True)),
                ('year_began', models.IntegerField(db_index=True)),
                ('year_ended', models.IntegerField(null=True, blank=True, default=0)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('publication_dates', models.CharField(max_length=255)),
                ('has_barcode', models.BooleanField(default=False)),
                ('has_indicia_frequency', models.BooleanField(default=False)),
                ('has_isbn', models.BooleanField(default=False)),
                ('has_issue_title', models.BooleanField(default=False)),
                ('has_volume', models.BooleanField(default=False)),
                ('has_rating', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('is_comics_publication', models.BooleanField(default=False)),
                ('is_singleton', models.BooleanField(default=False)),
                ('issue_count', models.IntegerField(null=True, blank=True, default=0)),
                ('has_gallery', models.BooleanField(default=False, db_index=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('open_reserve', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('cover_url', models.URLField(max_length=255, null=True, blank=True)),
                ('publication_type_id', models.IntegerField(null=True, blank=0)),
                ('country', models.ForeignKey(to='inventory.Country')),
                ('images', models.ManyToManyField(to='inventory.Image')),
                ('language', models.ForeignKey(to='inventory.Language')),
                ('publisher', models.ForeignKey(to='inventory.Publisher')),
            ],
            options={
                'db_table': 'gcd_series',
                'ordering': ['sort_name', 'year_began'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, blank=True, upload_to='upload')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(null=True, blank=True)),
                ('joined', models.DateField(null=True, blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('street_name', models.CharField(max_length=63)),
                ('street_number', models.CharField(max_length=31, null=True, blank=True)),
                ('unit_number', models.CharField(max_length=15, null=True, blank=True)),
                ('city', models.CharField(max_length=63)),
                ('province', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('postal', models.CharField(max_length=31)),
                ('website', models.URLField(null=True, blank=True)),
                ('email', models.EmailField(max_length=254, null=True, blank=True)),
                ('phone', models.CharField(max_length=31, null=True, blank=True)),
                ('fax', models.CharField(max_length=31, null=True, blank=True)),
                ('twitter_url', models.URLField(null=True, blank=True)),
                ('facebook_url', models.URLField(null=True, blank=True)),
                ('instagram_url', models.URLField(null=True, blank=True)),
                ('linkedin_url', models.URLField(null=True, blank=True)),
                ('github_url', models.URLField(null=True, blank=True)),
                ('google_url', models.URLField(null=True, blank=True)),
                ('youtube_url', models.URLField(null=True, blank=True)),
                ('flickr_url', models.URLField(null=True, blank=True)),
                ('organization', models.ForeignKey(to='inventory.Organization')),
            ],
            options={
                'db_table': 'ec_stores',
                'ordering': ('store_id',),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_inferred', models.BooleanField(default=False, db_index=True)),
                ('feature', models.CharField(max_length=255)),
                ('sequence_number', models.IntegerField()),
                ('page_count', models.DecimalField(max_digits=10, null=True, decimal_places=3, db_index=True)),
                ('page_count_uncertain', models.BooleanField(default=False, db_index=True)),
                ('script', models.TextField()),
                ('pencils', models.TextField()),
                ('inks', models.TextField()),
                ('colors', models.TextField()),
                ('letters', models.TextField()),
                ('editing', models.TextField()),
                ('no_script', models.BooleanField(default=False, db_index=True)),
                ('no_pencils', models.BooleanField(default=False, db_index=True)),
                ('no_inks', models.BooleanField(default=False, db_index=True)),
                ('no_colors', models.BooleanField(default=False, db_index=True)),
                ('no_letters', models.BooleanField(default=False, db_index=True)),
                ('no_editing', models.BooleanField(default=False, db_index=True)),
                ('job_number', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=255)),
                ('characters', models.TextField()),
                ('synopsis', models.TextField()),
                ('reprint_notes', models.TextField()),
                ('notes', models.TextField()),
                ('keywords', models.TextField(null=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('issue', models.ForeignKey(to='inventory.Issue')),
            ],
            options={
                'db_table': 'gcd_stories',
                'ordering': ('sequence_number',),
            },
        ),
        migrations.CreateModel(
            name='StoryType',
            fields=[
                ('story_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True, max_length=50, db_index=True)),
                ('sort_code', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'gcd_story_types',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.ForeignKey(to='inventory.StoryType'),
        ),
        migrations.AddField(
            model_name='section',
            name='store',
            field=models.ForeignKey(to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(to='inventory.Organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='store',
            field=models.ForeignKey(to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='issue',
            name='series',
            field=models.ForeignKey(null=True, to='inventory.Series'),
        ),
        migrations.AddField(
            model_name='indiciapublisher',
            name='parent',
            field=models.ForeignKey(null=True, to='inventory.Publisher'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(to='inventory.Organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comic',
            name='cover',
            field=models.ForeignKey(blank=True, to='inventory.ImageUpload', null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='images',
            field=models.ManyToManyField(blank=True, to='inventory.ImageUpload', related_name='comic_images'),
        ),
        migrations.AddField(
            model_name='comic',
            name='issue',
            field=models.ForeignKey(to='inventory.Issue'),
        ),
        migrations.AddField(
            model_name='comic',
            name='location',
            field=models.ForeignKey(blank=True, to='inventory.Location', null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='organization',
            field=models.ForeignKey(to='inventory.Organization'),
        ),
        migrations.AddField(
            model_name='comic',
            name='section',
            field=models.ForeignKey(blank=True, to='inventory.Section', null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='store',
            field=models.ForeignKey(to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='branduse',
            name='publisher',
            field=models.ForeignKey(to='inventory.Publisher'),
        ),
        migrations.AddField(
            model_name='brandgroup',
            name='parent',
            field=models.ForeignKey(null=True, to='inventory.Publisher'),
        ),
        migrations.AddField(
            model_name='brandemblemgroup',
            name='brandgroup',
            field=models.ForeignKey(null=True, to='inventory.BrandGroup'),
        ),
        migrations.AddField(
            model_name='brand',
            name='group',
            field=models.ManyToManyField(db_table='gcd_brand_emblem_group', blank=True, to='inventory.BrandGroup'),
        ),
        migrations.AddField(
            model_name='brand',
            name='images',
            field=models.ManyToManyField(to='inventory.Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='parent',
            field=models.ForeignKey(null=True, to='inventory.Publisher'),
        ),
    ]
